name: Test | Coverage

on:
  push:
    branches:
      - main
    # Only run when push includes commits with changes to:
    paths:
      - 'src/**/*.js'
      - 'test/**/*.{js,pot,po}'
      - 'jest.config.js'
      - 'package.json'

  pull_request:
    branches:
      - main
    # Only run when push includes commits with changes to:
    paths:
      - 'src/**/*.js'
      - 'test/**/*.{js,pot,po}'
      - 'jest.config.js'
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          # cache: 'npm'
      # - run: npm ci
      - run: npm install
      - run: npm test -- --coverage

      # Save coverage report in Coveralls
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: './test/coverage/lcov.info'
