name: Test | Coverage

on:
  push:
    branches:
      - main
    # Only run when push includes commits with changes to:
    paths:
      - 'src/**.js'
      - 'test/**.{js,pot,po}'
      - 'jest.config.js'
      - 'package.json'
      - 'package-lock.json'

  pull_request:
    branches:
      - main
    # Only run when push includes commits with changes to:
    paths:
      - 'src/**.js'
      - 'test/**.{js,pot,po}'
      - 'jest.config.js'
      - 'package.json'

jobs:
  collect_and_upload:
    name: Collect and upload test coverage
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Jest with coverage
        run: npm test -- --coverage

      # Save coverage report in Coveralls
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: './test/coverage/lcov.info'
