name: CI - Lint / Test / Version

on:
  push:
    branches:
      - main
    # Ignore version bumps
    tags-ignore:
      - 'v*'
    # Ignore workflow exclusive pushes
    paths-ignore:
      - '.github/**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          # cache: 'npm'
      - run: npm install
      - run: npm run lint

  test:
    name: Test (Node.js ${{ matrix.node-version }} on ${{ runner.os }})
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        node-version:
          # - 12.x
          # - 14.x
          - 16.x
        os:
         - ubuntu-latest
         - windows-latest
         # - macos-latest
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # cache: 'npm'
      - run: npm install
      - run: npm test

  version:
    name: Version
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/
      - run: git config --global user.name 'vHeemstra'
      - run: git config --global user.email '17368112+vHeemstra@users.noreply.github.com'
      - run: npm version major -m "Major release v%s"
        if: |
          startsWith(github.event.head_commit.message, 'breaking') ||
          startsWith(github.event.head_commit.message, 'major:')
      - run: npm version minor -m "Minor release v%s"
        if: |
          startsWith(github.event.head_commit.message, 'feat') ||
          startsWith(github.event.head_commit.message, 'minor:')
      - run: npm version patch -m "Patch release v%s"
        if: |
          !startsWith(github.event.head_commit.message, 'breaking') &&
          !startsWith(github.event.head_commit.message, 'major:') &&
          !startsWith(github.event.head_commit.message, 'feat') &&
          !startsWith(github.event.head_commit.message, 'minor:')
      - run: git push --follow-tags
