name: Manual run

on:
  workflow_dispatch:
    inputs:
      the_token:
        description: 'Token'
        required: true
        type: string
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.print_tags == 'true' }}
    steps:
      - name: Print the input tag to STDOUT
        run: echo The tags are ${{ github.event.inputs.tags }}

  dump_contexts_to_log:
    runs-on: ubuntu-latest
    env:
      MANUAL_TOKEN: ${{ secrets.MANUAL_RUN_CI_TOKEN }}
    steps:
      - name: Dump GitHub context
        if: ${{ github.event.inputs.the_token == env.MANUAL_TOKEN }}
        run: |
          echo '\n'
          echo 'github:\n'
          echo '${{ toJSON(github) }}'
          echo '\n'
          echo 'env:\n'
          echo '${{ toJSON(env) }}'
          echo '\n'
          echo 'job:\n'
          echo '${{ toJSON(job) }}'
          echo '\n'
          echo 'steps:\n'
          echo '${{ toJSON(steps) }}'
          echo '\n'
          echo 'runner:\n'
          echo '${{ toJSON(runner) }}'
          echo '\n'
          echo 'strategy:\n'
          echo '${{ toJSON(strategy) }}'
          echo '\n'
          echo 'matrix:\n'
          echo '${{ toJSON(matrix) }}'
          echo '\n'
          echo 'needs:\n'
          echo '${{ toJSON(needs) }}'
          echo '\n'
          echo 'inputs:\n'
          echo '${{ toJSON(inputs) }}'
      # - name: Check out repository
      #   uses: actions/checkout@v3
      #   with:
      #     token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      # - name: Install Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16.x
      #     registry-url: https://registry.npmjs.org/

      # # - run: git config --global user.name 'github-actions'
      # # - run: git config --global user.email 'github-actions@github.com'
      # - run: git config --global user.name 'vHeemstra'
      # - run: git config --global user.email '17368112+vHeemstra@users.noreply.github.com'
      # - run: npm install
